apiVersion: v1
kind: Plugin
metadata:
  author: lucasual
  name: Botflow
  repository: ''
  version: 0.1.0
  description:
    en_US: 更好的响应模式，支持分别发送图片和文本指令
    zh_Hans: 更好的响应模式，支持分别发送图片和文本指令
  label:
    en_US: Botflow
    zh_Hans: Botflow
  icon: assets/icon.svg
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: Botflow
